# Generated by Django 3.2.7 on 2021-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210913_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
