# Generated by Django 3.2.7 on 2021-09-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20210924_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
    ]
