# Generated by Django 3.2.7 on 2021-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_order_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5200)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
