# Generated by Django 3.2.7 on 2021-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='writer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
